create extension if not exists pgcrypto;

create table if not exists organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  organization_type text not null default 'other' check (organization_type in ('citizen_group', 'panchayat', 'municipality', 'government', 'university', 'industry', 'startup', 'msme', 'csr', 'research', 'innovation_hub', 'other')),
  description text,
  contact_email text,
  contact_phone text,
  website text,
  created_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  auth_user_id text not null unique,
  name text,
  email text,
  phone text,
  role text not null default 'citizen' check (role in ('citizen', 'university', 'industry', 'administrator', 'municipality')),
  organization_id bigint references organizations(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists problems (
  id bigint generated by default as identity primary key,
  submitter_user_id bigint references users(id) on delete set null,
  citizen_name text,
  problem_name text not null,
  description text not null,
  phone text not null,
  aadhar_last4 text,
  email text,
  location text not null,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  urgency_requested boolean not null default false,
  ai_urgency text not null default 'medium' check (ai_urgency in ('critical', 'high', 'medium', 'low')),
  category text not null default 'Community infrastructure',
  difficulty text not null default 'intermediate' check (difficulty in ('starter', 'intermediate', 'advanced')),
  status text not null default 'new' check (status in ('new', 'under_review', 'in_progress', 'solution_proposed', 'implemented')),
  assigned_university text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table solutions add column if not exists problem_id bigint references problems(id) on delete cascade;
alter table solutions add column if not exists author_user_id bigint references users(id) on delete set null;
alter table solutions add column if not exists solution_text text;
alter table solutions drop constraint if exists solutions_challenge_id_fkey;
update solutions set solution_text = coalesce(solution_text, description) where solution_text is null;

alter table collaborations add column if not exists problem_id bigint references problems(id) on delete cascade;
alter table collaborations add column if not exists organization_id bigint references organizations(id) on delete set null;
alter table collaborations add column if not exists user_ref bigint references users(id) on delete set null;
alter table collaborations add column if not exists collaboration_type text default 'other';
alter table collaborations add column if not exists contribution text;
alter table collaborations add column if not exists funding_amount numeric(14, 2) not null default 0;

alter table comments add column if not exists problem_id bigint references problems(id) on delete cascade;
alter table comments add column if not exists body text;
alter table comments add column if not exists author_user_ref bigint references users(id) on delete set null;
alter table comments drop constraint if exists comments_challenge_id_fkey;
update comments set body = coalesce(body, comment) where body is null;

alter table votes add column if not exists problem_id bigint references problems(id) on delete cascade;
alter table votes add column if not exists user_ref bigint references users(id) on delete cascade;
alter table votes add column if not exists value smallint not null default 1;
alter table votes drop constraint if exists votes_challenge_id_fkey;
alter table votes drop constraint if exists votes_value_check;
alter table votes add constraint votes_value_check check (value in (-1, 1));

create table if not exists attachments (
  id bigint generated by default as identity primary key,
  problem_id bigint references problems(id) on delete cascade,
  solution_id uuid references solutions(id) on delete cascade,
  uploaded_by_user_id bigint references users(id) on delete set null,
  url text not null,
  storage_key text,
  file_name text not null,
  mime_type text not null,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  created_at timestamptz not null default now(),
  check (problem_id is not null or solution_id is not null)
);

create table if not exists project_updates (
  id bigint generated by default as identity primary key,
  problem_id bigint not null references problems(id) on delete cascade,
  author_user_id bigint references users(id) on delete set null,
  author_role text not null,
  author_name text not null,
  body text not null,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists tech_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  event_date text not null,
  location text not null,
  university text not null,
  challenge_id bigint references problems(id) on delete set null,
  sponsorship_target numeric(14, 2) not null default 0,
  sponsor_raised numeric(14, 2) not null default 0,
  created_by_user_id bigint references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists event_sponsorships (
  id bigint generated by default as identity primary key,
  event_id bigint not null references tech_events(id) on delete cascade,
  industry_name text not null,
  industry_user_id bigint references users(id) on delete set null,
  amount numeric(14, 2) not null default 0,
  contribution_note text,
  created_at timestamptz not null default now()
);

create index if not exists problems_status_idx on problems(status);
create index if not exists problems_urgency_idx on problems(ai_urgency);
create index if not exists problems_created_at_idx on problems(created_at desc);
create index if not exists solutions_problem_id_idx on solutions(problem_id, created_at desc);
create index if not exists comments_problem_id_idx on comments(problem_id, created_at desc);
create index if not exists votes_problem_id_idx on votes(problem_id);
create index if not exists attachments_problem_id_idx on attachments(problem_id, created_at desc);
create index if not exists project_updates_problem_id_idx on project_updates(problem_id, created_at desc);
create index if not exists tech_events_created_at_idx on tech_events(created_at desc);

create or replace view problem_summary as
select
  p.*,
  latest.id as solution_id,
  latest.description as solution,
  coalesce(v.vote_count, 0) as vote_count
from problems p
left join lateral (
  select s.id, s.description
  from solutions s
  where s.problem_id = p.id
  order by s.created_at desc
  limit 1
) latest on true
left join lateral (
  select count(*)::int as vote_count
  from votes v
  where v.problem_id = p.id and v.value = 1
) v on true;
